server:
  port: 8088
  servlet:
    context-path: /
  session:
    cookie:
      name: JSESSIONID
security:
  basic:
    enabled: true
  oauth2:
    client:
      clientId: SampleClientId
      clientSecret: secret
      accessTokenUri: http://localhost:8090/auth/oauth/token
      userAuthorizationUri: http://localhost:8090/auth/oauth/authorize
    resource:
      userInfoUri: http://localhost:8090/auth/user/me
spring:
  thymeleaf:
    cache: false
authorization: http://localhost:8090/auth