server:
  port: 8088
  servlet:
    context-path: /
  session:
    cookie:
      name: JSESSIONID
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: simpleClient
      clientSecret: secret
      accessTokenUri: http://localhost:8090/popov/oauth/token
      userAuthorizationUri: http://localhost:8090/popov/oauth/authorize
    resource:
      userInfoUri: http://localhost:8090/popov/user/me
spring:
  thymeleaf:
    cache: false